server:
  port: 1111

logging:
  level:
    org.springframework.cloud.openfeign: debug
    org.springframework.cloud.sleuth: debug
    org.springframework.http.server.reactive: debug
    org.springframework.web.reactive: debug
    reactor.ipc.netty: debug

# Hystrix 断路器 2s超时，超时请求策略
hystrix:
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
          thread:
            timeoutInMilliseconds: 5000

spring:
  main:
    allow-bean-definition-overriding: true  # Bean重名覆盖
  application:
    name: ltts-gateway-server


  cloud:
    ############################### 网关路由策略配置 #############################
    gateway:
      discovery:
        locator:
          lowerCaseServiceId: true
          enabled: true
      routes:
        - id: ltts-order
          uri: lb://ltts-order           # lb loadbalance 采用负载均衡算法
          predicates:
            - Path=/order-service/**      # 请求的路径匹配则会转发到uri
          filters:
            - Authentication=/*           # 自定义拦截器
            - StripPrefix=1               # 移除path中的第一个路径order-service
            - name: RequestRateLimiter   # 限流
              args:
                deny-empty-key: true
                keyResolver: '#{@ipKeyResolver}'
                redis-rate-limiter.replenishRate: 1  # 每秒补充10个
                redis-rate-limiter.burstCapacity: 20 # 突发20个
                redis-rate-limiter.requestedTokens: 1 # 每次请求消耗1个
      default-filters:  # 默认过滤器，熔断Hystrix
#      - name: Hystrix
#        args:
#          name : default
#          fallbackUri: 'forward:/defaultFallback'
      global-filter:
        - name: Sentinel
    ############################### sentinel 规则配置 #############################
    sentinel:
      enabled: true
      eager: true
      transport:
        dashboard: localhost:8080
      datasource:
        ds1:
          file:
            file: "classpath:flowrule.json"
            data-type: json
            rule-type: flow
#        ds1:
#          nacos:
#            server-addr: ${nacos.server-addr}
#            dataId: ltts-gateway-sentinel
#            groupId: ${nacos.gruop}
#            data-type: json
#            rule-type: flow
  ############################### 链路追踪配置 #############################
  zipkin:
    enabled: false
    base-url: http://localhost:9411  # zipserver端
  sleuth:
    enabled: false
    sampler:
      probability: 1 # 采样比例 默认0.1,测试改成1.0
  ############################### sentinel #############################


##动态路由配置开关，开启则从配置中心获取，否者读取本地的配置
gateway:
  dynamic:
    route:
      enabled: false



# 拦截的请求ip地址
blackIpList: "198.*"




























